version: 2
updates:
- package-ecosystem: npm
  directory: "/dashboard"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/api"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
