# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "sinatra", "~> 3.0"

gem "json", "~> 2.6"

gem "sinatra-contrib", "~> 3.0"

gem "mysql2", "~> 0.5.4"

gem "csv", "~> 3.2"

gem "byebug", "~> 11.1", :group => :development

gem "rom-sql", "~> 3.5"

gem "puma", "~> 5.6", :group => :development
