# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "sinatra", "~> 4.2"

gem "json", "~> 2.18"

gem "sinatra-contrib", "~> 4.2"

gem "mysql2", "~> 0.5.7"

gem "csv", "~> 3.3"

gem "rom-sql", "~> 3.7"

group :development, :test do
  gem "byebug", "~> 12.0"
  gem "puma", "~> 7.1"
  gem "rspec", "~> 3.12"
  gem "rack-test", "~> 2.1"
end
