# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "sinatra", "~> 2.1"

gem "json", "~> 2.5"

gem "sinatra-contrib", "~> 2.1"

gem "mysql2", "~> 0.5.3"

gem "csv", "~> 3.1"

gem "byebug", "~> 11.1", :group => :development

gem "rom-sql", "~> 3.2"
