name: Build and Deploy
on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup Node ⚙️
        uses: actions/setup-node@v7
        with:
          node-version-file: dashboard/.nvmrc
          cache: yarn
          cache-dependency-path: dashboard/yarn.lock

      - name: Install and Build 🔧
        run: |
          cd dashboard
          sed -i 's|createWebHistory("/dashboard/")|createWebHistory("/vlinder/")|g' src/router/index.ts
          yarn install --frozen-lockfile
          yarn build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dashboard/dist
